### ISSUE TITLE
Designate that the theme is D9 compatible

### ISSUE THREAD

**Issue by ssh6** [CU-CommunityApps/cwd_admin#6]
Per upgrade_status module:

Add core_version_requirement: ^8 || ^9 to designate that the module is compatible with Drupal 9. See https://drupal.org/node/3070687.

themes/custom/cwd_admin/cwd_admin.info.yml

**Comment by stacypendell** [comment]
Hi Sean, thanks, that's already on our list - I've just been figuring out whether there are other updates ready to include at the same time.

**Comment by alisonjo315** [comment]
All done! -- 2756ae1e9698d633e6367b383abb726ab023d2b2
